---
title: "Final Project"
subtitle: "Part 1"
format: 
  html:
    self-contained: true
    code-tools: true
    toc: true
    number-sections: true
editor: source
execute: 
  error: true
  echo: true
  message: false
  warning: false
---

Setup

```{r setup}
#| include: false
library(tidyverse)
library(glue)
library(english)

```

Uploading data

```{r}
hapi <- read.csv("hapiscore_whr.csv")
life <- read.csv("lex.csv")
view(hapi)
view(life)
```

Data Cleaning
```{r}
hapi |>
  mutate(across(.cols=X2005:X2022, .fns = as.numeric))
life |>
  select(X2005:X2022) |>
  mutate(across(.cols=everything(), .fns = as.numeric)) |>
  
```
- All of the happiness scores and life expectancies are numbers, so we converted these values to the numeric type. 
- Additionally, the happiness score data set only contains data from the years 2005-2022. So, we only selected those rows from the life expectancy so that they will have an equal amount of columns and years.


Pivot Longer

```{r}
hapiscore <- hapi %>% 
                pivot_longer(cols = -country, 
                             names_to = "year", 
                             values_to = "happiness_score")

lex <- life %>% 
          pivot_longer(cols = -country, 
                       names_to = "year", 
                       values_to = "lex")

```

```{r}
data <- hapiscore %>%
    inner_join(lex, by = c("country","year"))
```

```{r}
head(data)
```
